name: ssh command
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - name: Setup SSH Agent
      #   uses: webfactory/ssh-agent@v0.7.0
      #   with:
      #     ssh-private-key: ${{ secrets.DEV_SSHE_SSH_KEY }}
      # - name: Run deploy script
      #   run: ssh -o StrictHostKeyChecking=no ${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_SSH_HOST }} bash /app/${{ secrets.DEV_SSH_USER }}/deploy.sh ${{ secrets.DEV_SSH_USER }}

      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}
      - run: |
          ssh ${{ steps.ssh.outputs.SERVER }} bash /app/ryuya_yoshida/deploy.sh ryuya_yoshida "
            export SESSION_SECRET='${{ secrets.SESSION_SECRET }}' &&
            export POSTGRES_USER='${{ secrets.POSTGRES_USER }}' &&
            export POSTGRES_DB='${{ secrets.POSTGRES_DB }}' &&
            export POSTGRES_HOST='${{ secrets.POSTGRES_HOST }}' &&
            export POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}' &&
            cd /app/ryuya_yoshida &&
            bash deploy.sh ryuya_yoshida
          "
        # env:
        #   POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        #   POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        #   POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        #   POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        #   # CLIENT_ORIGIN: ${{ secrets.CLIENT_ORIGIN }}
        #   SESSION_SECRET: ${{ secrets.SESSION_SECRET }}